spring:
  application:
    name: ms-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    mongodb:
      uri: mongodb://localhost:27017/everis

server:
  port: 8080
  shutdown: graceful

jwt:
  secret: '123456789'

swagger:
  basePackageScan: com.bci.msuser.controller



