spring:
  application:
    name: ms-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    mongodb:
      uri: mongodb://localhost:27017/'{your app db}'

server:
  port: 8080
  shutdown: graceful

jwt:
  secret: '{your app secret}'

swagger:
  basePackageScan: com.bci.msuser.controller



